// Code generated by "stringer -type=Op"; DO NOT EDIT

package mix

import "fmt"

const _Op_name = "LDALD1LD2LD3LD4LD5LD6LDXLDANLD1NLD2NLD3NLD4NLD5NLD6NLDXNSTAST1ST2ST3ST4ST5ST6STX"

var _Op_index = [...]uint8{0, 3, 6, 9, 12, 15, 18, 21, 24, 28, 32, 36, 40, 44, 48, 52, 56, 59, 62, 65, 68, 71, 74, 77, 80}

func (i Op) String() string {
	i -= 8
	if i >= Op(len(_Op_index)-1) {
		return fmt.Sprintf("Op(%d)", i+8)
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
